# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
version: '2'

issues:
  max-same-issues: 0

linters:
  default: none
  enable:
    - durationcheck
    - errcheck
    - copyloopvar
    - forcetypeassert
    - godot
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - usetesting

formatters:
  enable:
    - gofmt
